### ISSUE TITLE
Unable to import AzureObjectAnchors.SDK folder and some errors

### ISSUE THREAD

**Issue by ananyanandi31** [Azure/azure-object-anchors#20] opened 2022-03-09 09:05 UTC
**Description**

Hi, I am trying to run the sample MRTK project on Hololens2. I updated the project to Unity 2020.3.21f1 version. Then, I added Azure Object Anchors feature using the MixedRealityFeatureTool and modified my Build settings to Universal Windows Platform. But I am facing some errors - 

1. "error CS0246: The type or namespace name 'EnvironmentObservationTopology' could not be found (are you missing a using directive or an assembly reference?)"
2. "error CS0246: The type or namespace name 'EnvironmentObservation' could not be found (are you missing a using directive or an assembly reference?)"
3. "error CS0246: The type or namespace name 'MultiAnchorObjectPlacement' could not be found (are you missing a using directive or an assembly reference?)"

Another unusual problem is that even after importing Azure Object Anchors from the MRFT, the AzureObjectAnchors.SDK folder is not visible in the Assets folder.

**Expected behavior**

No errors, so that the project can be built and run on a HoloLens 2 device.

**Development information**

 - OS: Windows
 - Development Platform\Version: Visual Studio 2019, Unity 2020.3.21f1
 - Azure Object Anchors 0.13.0

**AR Device information (please complete the following information):**

 - HoloLens 2
 - OS: Windows

**Comment by craigktreasure** [comment] 2022-03-09 15:20
Appears to be a duplicate of #19.

**Closed by craigktreasure** 2022-03-09 15:20 UTC

**Comment by blackbelt-violinist** [comment] 2022-03-18 20:54
Is it normal that the folder AzureObjectAnchors.SDK is not in github project?

**Comment by craigktreasure** [comment] 2022-03-18 22:07
Yes. That comes into your project when after you import the Azure Object Anchors UPM package using the Mixed Reality Feature Tool.

**Comment by blackbelt-violinist** [comment] 2022-03-19 20:20
UPM package?
I've tried getting just Azure Object Anchors and I've tried getting all features.
When I get all features, I definitively get a AzureSpatialAnchors.SDK folder.
When i get just Azure Object Anchors, I don't get the AzureObjectAnchors.SDK folder like in the tutorial

![image](https://user-images.githubusercontent.com/51131762/159137186-9e6985b5-7f18-440b-8b1f-3bfa948066ab.png)

**Comment by craigktreasure** [comment] 2022-03-20 15:19
I see the confusion. Expand the "packages" fielder and you'll see the Object Anchors SDK package contents. Object Anchors doesn't import anything into your "assets" folder, so you shouldn't see anything like that in there.

UPM is the [Unity Package Manager](https://docs.unity3d.com/Manual/Packages.html). All the packages you installed are UPM packages.
